type: object
properties:
  engine:
    type: string
    enum:
      - postgresql
  host:
    type: string
  port:
    type: integer
    minimum: 1
    maximum: 65535
  name:
    type: string
  user:
    type: string
  password:
    type: string
  params:
    type: object
additionalProperties: true
required:
  - engine
ependencies:
  port:
    - host
  password:
    - user