"""20201023t182601

Revision ID: b94f62254354
Revises: 3ff1ec9f0e1e
Create Date: 2020-10-23 18:26:01.614342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94f62254354'
down_revision = '3ff1ec9f0e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follower_states', sa.Column('data', sa.Unicode(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follower_states', 'data')
    # ### end Alembic commands ###
