version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(asctime)23s [%(levelname)8s] [DEFAULT] %(module)s/%(lineno)d: %(message)s"
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  gino:
    handlers: []
    propagate: false
  sqlalchemy:
    handlers: []
    propagate: false
  "":
    handlers:
      - default
    level: NOTSET
    propagate: false
